In [8]:
import h5py as h5
import numpy as np
import scipy.stats as st

n_ch = 16

with h5.File('test_features.h5') as features:
    with h5.File('test.h5', 'r') as train:
        if not 'names' in features:
            features.create_dataset('names', data = train['names'][:])
        for i in range(n_ch):
            ch = 'ch%d' % i
            print(ch + '...')
            n_cases = train[ch].shape[0]
            if not ch in features:
                features.create_dataset(ch, (n_cases, 4))
            for j in range(n_cases):
                
                features[ch][j, 0] = train[ch][j].mean()
                features[ch][j, 1] = train[ch][j].std()
                features[ch][j, 2] = st.kurtosis(train[ch][j])
                features[ch][j, 3] = st.skew(train[ch][j])
                if j % 50 == 0:
                    print('%d/%d' % (j, n_cases))
            
    

ch0...
0/6126
50/6126
100/6126
150/6126
200/6126
250/6126
300/6126
350/6126
400/6126
450/6126
500/6126
550/6126
600/6126
650/6126
700/6126
750/6126
800/6126
850/6126
900/6126
950/6126
1000/6126
1050/6126
1100/6126
1150/6126
1200/6126
1250/6126
1300/6126
1350/6126
1400/6126
1450/6126
1500/6126
1550/6126
1600/6126
1650/6126
1700/6126
1750/6126
1800/6126
1850/6126
1900/6126
1950/6126
2000/6126
2050/6126
2100/6126
2150/6126
2200/6126
2250/6126
2300/6126
2350/6126
2400/6126
2450/6126
2500/6126
2550/6126
2600/6126
2650/6126
2700/6126
2750/6126
2800/6126
2850/6126
2900/6126
2950/6126
3000/6126
3050/6126
3100/6126
3150/6126
3200/6126
3250/6126
3300/6126
3350/6126
3400/6126
3450/6126
3500/6126
3550/6126
3600/6126
3650/6126
3700/6126
3750/6126
3800/6126
3850/6126
3900/6126
3950/6126
4000/6126
4050/6126
4100/6126
4150/6126
4200/6126
4250/6126
4300/6126
4350/6126
4400/6126
4450/6126
4500/6126
4550/6126
4600/6126
4650/6126
4700/6126
4750/6126
4800/6126
4850/6126
4900/6126
4950/6126
5000/6126
5050/6

In [9]:
import h5py as h5

with h5.File('test_features.h5') as features:
    print(features['ch0'][:])

[[ -1.07828775e-07   3.48321037e+01   2.69216847e+00  -1.45754695e-01]
 [  4.06901037e-08   2.92932129e+01   2.96235633e+00  -2.04759195e-01]
 [  7.54801420e-07   2.96426067e+01   2.22492599e+00  -2.19310790e-01]
 ..., 
 [  1.12304690e-06   3.78931732e+01   1.94814861e+00  -3.67483020e-01]
 [ -2.22981771e-06   8.66706238e+01   2.52038240e+00  -4.05322582e-01]
 [  3.33658846e-07   1.06438812e+02   1.28049994e+00  -1.40879020e-01]]
